version: "3"
services:
  webhook-relay:
    container_name: webhook_relay
    image: ghcr.io/rojosinalma/webhook-relay:main
    ports:
      - '50000:50000'
    environment:
      - RELAY_HOST=0.0.0.0
      - RELAY_PORT=50000
      - RELAY_DST_URL=http://localhost:50001

  webhook-relay-test:
    container_name: webhook_relay_test
    image: ghcr.io/rojosinalma/webhook-relay:main
    command: gunicorn -w 1 -b 0.0.0.0:5001 dst_api_test:app
    networks:
      - common
    ports:
      - '50001:50001'
